title = "Let's Encrypt"
contentDir = "content/he"
languageName = "עברית"
languageCode = "he"
weight = 10

[params]
beforeColon = ""
description = """
  Let's Encrypt היא רשות אישורים חופשית, אוטומטית ופתוחה
  שמוגשת לך באדיבות <a href="https://www.abetterinternet.org/">קבוצת מחקר אבטחת האינטרנט (ISRG)</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/he_IL/i/btn/btn_donateCC_LG.gif"
paypalCountry = "IL"
numberFormat = "-|.|,"
viewInThatLanguage = "לעבור לעברית"
