title = "Let's Encrypt"
contentDir = "content/cs"
label = "Čeština"
locale = "cs-CZ"
weight = 150

[params]
beforeColon = ""
description = "Let's Encrypt je bezplatná, automatizovaná a otevřená certifikační autorita provozovaná neziskovou organizací <a href=\"https://www.abetterinternet.org/\">Internet Security Research Group (ISRG)</a>. O naší práci se dočtete ve <a href=\"https://www.abetterinternet.org/annual-reports/\">výroční zprávě</a>."
paypalDonateImage = "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"
numberFormat = "-|,| "
viewInThatLanguage = "Zobraz česky"
