title = "Let's Encrypt - Certificados SSL/TLS Gratuitos"
contentDir = "content/es"
languageName = "Espa침ol"
languageCode = "es-US"
beforeColon = "&nbsp;"
weight = 250
description = """
  Let's Encrypt es una autoridad de certificaci칩n gratuita, automatizada, y abierta traida a ustedes por la organizaci칩n sin 치nimos de lucro <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/es_XC/i/btn/btn_donateCC_LG.gif"
paypalCountry = "ES"
numberFormat = "-|.|,"
