title = "Let's Encrypt"
contentDir = "content/cs"
languageName = "Čeština"
languageCode = "cs-CZ"
weight = 10

[params]
beforeColon = ""
description = """
Let's Encrypt je bezplatná, automatizovaná a otevřená certifikační autorita, kterou vám přináší nezisková organizace <a href="https://www.abetterinternet.org/">Internet Security Research Group (ISRG)</a>. Vše o naší letošní neziskové práci si můžete přečíst v naší <a href="https://www.abetterinternet.org/annual-reports/">výroční zprávě za rok 2023</a>.
"""
paypalDonateImage = "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif"
paypalCountry = "US"
numberFormat = "-|,| "
viewInThatLanguage = "Zobraz v angličtině"
