[[main]]
name = "උදව් ගන්න"
weight = 20
url = "https://community.letsencrypt.org/"
[[main]]
name = "පරිත්‍යාග"
weight = 30
identifier = "donate"
[[main]]
name = "අප ගැන"
weight = 40
identifier = "about"
[[main]]
name = "අන්තර්ජාල ආරක්‍ෂණ පර්යේෂණ සමූහය (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "සේවාවේ තත්‍වය"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "වෘත්තීන්"
weight = 80
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
