[[main]]
name = "උදව් ගන්න"
weight = 20
url = "https://community.letsencrypt.org/"

[[main]]
name = "ලඝුපත"
weight = 25
url = "/blog/"

[[main]]
name = "පරිත්‍යාග"
weight = 30
identifier = "donate"

[[main]]
name = "අනුග්‍රහකයෙක් වන්න"
weight = 40
identifier = "become-a-sponsor"
parent = "donate"
url = "https://www.abetterinternet.org/sponsor/"

[[main]]
name = "අනුග්‍රහකයින් හා මූල්‍යදායකයින්"
weight = 40
identifier = "sponsors"
parent = "donate"
url = "https://www.abetterinternet.org/sponsors/"

[[main]]
name = "අප ගැන"
weight = 40
identifier = "about"

[[main]]
name = "අන්තර්ජාල ආරක්‍ෂණ පර්යේෂණ සමූහය (ISRG)"
weight = 200
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"

[[main]]
name = "සේවාවේ තත්‍වය"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"

[[main]]
name = "වෘත්තීන්"
weight = 110
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"

[[main]]
name = "වාර්ෂික වාර්තා"
weight = 140
identifier = "annual-reports"
parent = "about"
url = "https://www.abetterinternet.org/annual-reports/"
