[[main]]
name = "Aconseguir ajuda"
weight = 20
url = "https://community.letsencrypt.org/"
[[main]]
name = "Fer un donatiu"
weight = 30
identifier = "donate"
[[main]]
name = "Quant a"
weight = 40
identifier = "about"
[[main]]
name = "Internet Security Research Group (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "Estat del servei"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "Treballa amb nosaltres"
weight = 80
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
[[main]]
name = "Become a Sponsor"
weight = 40
identifier = "become-a-sponsor"
parent = "donate"
url = "https://www.abetterinternet.org/sponsor/"
