[[main]]
name = "도움말"
weight = 20
url = "https://community.letsencrypt.org/"
[[main]]
name = "후원"
weight = 30
identifier = "donate"
url = "/ko/donate/"
[[main]]
name = "소개"
weight = 40
identifier = "about"
url = "/ko/about/"
[[main]]
name = "비영리 인터넷 보안 연구 그룹 (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "서비스 상태"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "채용"
weight = 80
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
