[[main]]
name = "Yardım Alın"
weight = 20
url = "https://community.letsencrypt.org/"
[[main]]
name = "Blog"
weight = 25
url = "/blog/"

[[main]]
name = "Bağış Yap"
weight = 30
identifier = "donate"

[[main]]
name = "Hakkımızda"
weight = 40
identifier = "about"

[[main]]
name = "İnternet Güvenliği Araştırma Grubu (ISRG)"
weight = 200
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"

[[main]]
name = "Servis Durumu"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"

[[main]]
name = "Kariyer"
weight = 110
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"

[[main]]
name = "Sponsor Olun"
weight = 40
identifier = "become-a-sponsor"
parent = "donate"
url = "https://www.abetterinternet.org/sponsor/"
