[[main]]
name = "Dapatkan Bantuan"
weight = 20
url = "https://community.letsencrypt.org/"
[[main]]
name = "Donasi"
weight = 30
identifier = "donate"
url = "/id/donate/"
[[main]]
name = "Tentang Kami"
weight = 40
identifier = "about"
url = "/id/about/"
[[main]]
name = "Internet Security Research Group (ISRG)"
weight = 20
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"
[[main]]
name = "Status Layanan"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"
[[main]]
name = "Karir"
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"
