[[main]]
name = "Obter Ajuda"
weight = 20
url = "https://community.letsencrypt.org/"

[[main]]
name = "Blog"
weight = 25
url = "/blog/"

[[main]]
name = "Doações"
weight = 30
identifier = "donate"

[[main]]
name = "Torne-se um Patrocinador"
weight = 40
identifier = "become-a-sponsor"
parent = "donate"
url = "https://www.abetterinternet.org/sponsor/"

[[main]]
name = "Patrocinadores e Doadores Atuais"
weight = 40
identifier = "sponsors"
parent = "donate"
url = "https://www.abetterinternet.org/sponsors/"

[[main]]
name = "Sobre Nós"
weight = 40
identifier = "about"

[[main]]
name = "Grupo de Pesquisa em Segurança da Internet (ISRG)"
weight = 200
identifier = "isrg"
parent = "about"
url = "https://www.abetterinternet.org/about/"

[[main]]
name = "Status do Serviço"
weight = 60
identifier = "status"
parent = "about"
url = "https://letsencrypt.status.io/"

[[main]]
name = "Carreiras"
weight = 110
identifier = "careers"
parent = "about"
url = "https://www.abetterinternet.org/careers/"

[[main]]
name = "Relatórios Anuais"
weight = 140
identifier = "annual-reports"
parent = "about"
url = "https://www.abetterinternet.org/annual-reports/"
