[[मुख्य]]
नाम = "सहायता प्राप्त करें"
भार = 20
url = "https://community.letsencrypt.org/"
[[मुख्य]]
नाम = "दान"
भार = 30
पहचानकर्ता = "दान"
url = "/ दान /"
[[मुख्य]]
नाम = "हमारे बारे में"
वजन = 40
पहचानकर्ता = "के बारे में"
url = "/about/"
[[मुख्य]]
नाम = "इंटरनेट सुरक्षा अनुसंधान समूह (ISRG)"
भार = 20
पहचानकर्ता = "isrg"
जनक = "के बारे में"
url = "https://www.abetterinternet.org/about/"
[[मुख्य]]
नाम = "सेवा की स्थिति"
वजन = 60
पहचानकर्ता = "स्थिति"
जनक = "के बारे में"
url = "https://letsencrypt.status.io/"
[[मुख्य]]
नाम = "करियर"
वजन = 80
पहचानकर्ता = "करियर"
जनक = "के बारे में"
url = "https://www.abetterinternet.org/careers/"
