# Site settings
title: Baiduio | 免费空间
description: >
  Baiduio 是一个免费空间提供商
baseurl: ""
url: "https://www.baiduio.ga/"
github_username: Baiduio 
twitter_username: 
crowdfunding_url: ""

# Build settings
markdown: kramdown
safe: true
timezone: America/Los_Angeles
encoding: utf-8
